// Curación de presentación al cliente del I-485 — preguntas legales de
// elegibilidad e inadmisibilidad (Part 9), agrupadas por tema y en español
// simple. Los SIJ están exentos de casi todos estos motivos: por eso la carga
// pública (ítems 56-66) se omite y el resto va con respuesta "No" por defecto.
// FUENTE DE VERDAD editable a mano: el texto sale del tooltip oficial de cada
// campo (ver scripts/i485-tooltips.json). Cada radio Sí/No mapea a su checkbox
// real por on-value en `real`. Composición e integridad en ../i485-client-form.ts.
import type { CuratedSection } from '../i485-client-form'

export const LEGAL_SECTIONS: CuratedSection[] = [
// ── 20. Tu historial migratorio ───────────────────────────────────────
  {
    id: 20,
    titleEs: 'Tu historial migratorio',
    descriptionEs:
      'Estas preguntas son sobre tus entradas, visas y trámites con inmigración. La mayoría de las personas responde No a todo esto. Si alguna te genera duda, déjala en No y coméntala con tu asesora Vanessa.',
    fields: [
      {
        key: 'v_p9_1',
        type: 'radio',
        labelEs:
          '¿Alguna vez has sido miembro o has estado relacionado con alguna organización, asociación, fondo, partido, club o grupo parecido, en Estados Unidos o en cualquier otro país?',
        helpEs: 'Esto incluye cualquier grupo en cualquier parte del mundo. La mayoría de las personas responde No.',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'historial',
        real: { Y: 'pt8line1_yesno_1', N: 'pt8line1_yesno' },
      },
      {
        key: 'pt9line2_organization1',
        type: 'text',
        labelEs: 'Nombre de la organización (primera)',
        helpEs: 'Solo si respondiste Sí arriba.',
        groupKey: 'historial',
        dependsOn: { key: 'v_p9_1', equals: 'Y' },
      },
      {
        key: 'pt9line6_organization2',
        type: 'text',
        labelEs: 'Nombre de la segunda organización (si hubo otra)',
        helpEs: 'Déjalo vacío si solo perteneciste a una.',
        groupKey: 'historial',
        dependsOn: { key: 'v_p9_1', equals: 'Y' },
      },

      {
        key: 'v_p9_10',
        type: 'radio',
        labelEs: '¿Alguna vez te han negado la entrada a Estados Unidos?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'historial',
        real: { Y: 'pt9line10_yesno_1', N: 'pt9line10_yesno' },
      },
      {
        key: 'v_p9_11',
        type: 'radio',
        labelEs: '¿Alguna vez te han negado una visa para Estados Unidos?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'historial',
        real: { Y: 'pt9line11_yesno', N: 'pt9line11_yesno_1' },
      },
      {
        key: 'v_p9_12',
        type: 'radio',
        labelEs: '¿Alguna vez has trabajado en Estados Unidos sin permiso de trabajo?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'historial',
        real: { Y: 'pt9line12_yesno', N: 'pt9line12_yesno_1' },
      },
      {
        key: 'v_p9_13',
        type: 'radio',
        labelEs: '¿Alguna vez has incumplido las condiciones de tu visa o de tu estatus migratorio?',
        helpEs: 'Por ejemplo, quedarte más tiempo del permitido o hacer algo que tu visa no permitía.',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'historial',
        real: { Y: 'pt8line13_yesno_1', N: 'pt8line13_yesno' },
      },
      {
        key: 'v_p9_14',
        type: 'radio',
        labelEs:
          '¿Estás ahora, o has estado alguna vez, en un proceso de deportación, exclusión o remoción (incluyendo remoción acelerada)?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'historial',
        real: { Y: 'pt8line18_yesno', N: 'pt8line18_yesno_1' },
      },
      {
        key: 'v_p9_15',
        type: 'radio',
        labelEs: '¿Alguna vez te han dado una orden final de exclusión, deportación o remoción?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'historial',
        real: { Y: 'pt8line19_yesno_1', N: 'pt8line19_yesno' },
      },
      {
        key: 'v_p9_16',
        type: 'radio',
        labelEs: '¿Alguna vez te han reactivado (puesto de nuevo en vigor) una orden anterior de deportación o remoción?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'historial',
        real: { Y: 'pt8line20_yesno', N: 'pt8line20_yesno_1' },
      },
      {
        key: 'v_p9_17',
        type: 'radio',
        labelEs:
          '¿Alguna vez un oficial o un juez de inmigración te concedió salida voluntaria, pero no saliste del país dentro del tiempo que te dieron?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'historial',
        real: { Y: 'pt8line17_yesno', N: 'pt8line17_yesno_1' },
      },
      {
        key: 'v_p9_18',
        type: 'radio',
        labelEs: '¿Alguna vez has solicitado algún tipo de alivio o protección contra la deportación o remoción?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'historial',
        real: { Y: 'pt8line23_yesno_1', N: 'pt8line23_yesno' },
      },
      {
        key: 'v_p9_19',
        type: 'radio',
        labelEs:
          '¿Alguna vez tuviste una visa J de intercambio (visitor) que te obligaba a regresar dos años a tu país?',
        helpEs: 'Esto solo aplica a quienes tuvieron una visa de intercambio J-1 o J-2.',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'historial',
        real: { Y: 'pt8line24a_yesno', N: 'pt8line24a_yesno_1' },
      },
      {
        key: 'v_p9_20',
        type: 'radio',
        labelEs: 'Si respondiste Sí arriba: ¿ya cumpliste con ese requisito de residir dos años en tu país?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'historial',
        dependsOn: { key: 'v_p9_19', equals: 'Y' },
        real: { Y: 'pt8line24b_yesno_1', N: 'pt8line24b_yesno' },
      },
      {
        key: 'v_p9_21',
        type: 'radio',
        labelEs:
          'Si tenías ese requisito y no lo cumpliste: ¿te dieron un perdón (waiver) o el Departamento de Estado recomendó uno a tu favor?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'historial',
        dependsOn: { key: 'v_p9_19', equals: 'Y' },
        real: { Y: 'pt8line24c_yesno', N: 'pt8line24c_yesno_1' },
      },
    ],
  },

  // ── 21. Antecedentes y delitos ─────────────────────────────────────────
  {
    id: 21,
    titleEs: 'Antecedentes y delitos',
    descriptionEs:
      'Estas preguntas son sobre arrestos, delitos o problemas con la ley, en cualquier país. La mayoría de las personas responde No a todo esto. Si alguna te genera duda, déjala en No y coméntala con tu asesora Vanessa.',
    fields: [
      {
        key: 'v_p9_22',
        type: 'radio',
        labelEs:
          '¿Alguna vez te han arrestado, citado, acusado o detenido por cualquier autoridad, en este o en cualquier otro país?',
        helpEs:
          'Contesta Sí aunque tu registro haya sido sellado o borrado, o aunque alguien te haya dicho que ya no tienes antecedentes. Aun así, la mayoría de las personas responde No.',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line22_yesno', N: 'pt8line22_yesno_1' },
      },
      {
        key: 'v_p9_23',
        type: 'radio',
        labelEs: '¿Alguna vez has cometido algún delito, aunque no te hayan arrestado ni acusado por él?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt9line23_yesno_1', N: 'pt9line23_yesno' },
      },
      {
        key: 'v_p9_24',
        type: 'radio',
        labelEs: '¿Alguna vez te has declarado culpable o te han condenado por un delito?',
        helpEs: 'Contesta Sí aunque después te hayan borrado el caso o te hayan dado un perdón. La mayoría de las personas responde No.',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt9line24_yesno', N: 'pt9line24_yesno_1' },
      },
      {
        key: 'v_p9_25',
        type: 'radio',
        labelEs:
          '¿Alguna vez un juez te ha castigado o te ha impuesto condiciones que limitaron tu libertad (cárcel, arresto domiciliario, libertad condicional, servicio comunitario, programas, etc.)?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line25_yesno_1', N: 'pt8line25_yesno' },
      },
      {
        key: 'v_p9_26',
        type: 'radio',
        labelEs: '¿Alguna vez has violado (o intentado violar) alguna ley sobre drogas o sustancias controladas?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line26_yesno_1', N: 'pt8line26_yesno' },
      },
      {
        key: 'v_p9_27',
        type: 'radio',
        labelEs: '¿Alguna vez has traficado drogas, o ayudado a alguien a traficar drogas, o te has beneficiado de eso?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line27_yesno_1', N: 'pt8line27_yesno' },
      },
      {
        key: 'v_p9_28',
        type: 'radio',
        labelEs:
          '¿Eres esposo(a), hijo o hija de alguien que traficó drogas, y recibiste algún beneficio económico de esa actividad en los últimos cinco años?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line28_yesno_1', N: 'pt8line28_yesno' },
      },
      {
        key: 'v_p9_29',
        type: 'radio',
        labelEs: 'Si respondiste Sí arriba: ¿sabías (o debías saber) que ese beneficio venía de esa actividad?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        dependsOn: { key: 'v_p9_28', equals: 'Y' },
        real: { Y: 'pt8line29_yesno_1', N: 'pt8line29_yesno' },
      },
      {
        key: 'v_p9_30',
        type: 'radio',
        labelEs: '¿Alguna vez te has dedicado a la prostitución, o vienes a Estados Unidos para dedicarte a ella?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line30_yesno_1', N: 'pt8line30_yesno' },
      },
      {
        key: 'v_p9_31',
        type: 'radio',
        labelEs: '¿Alguna vez has conseguido o llevado personas para la prostitución (proxenetismo)?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line31_yesno', N: 'pt8line31_yesno_1' },
      },
      {
        key: 'v_p9_32',
        type: 'radio',
        labelEs: '¿Alguna vez has recibido dinero o ganancias de la prostitución?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line32_yesno', N: 'pt8line32_yesno_1' },
      },
      {
        key: 'v_p9_33',
        type: 'radio',
        labelEs:
          '¿Piensas dedicarte en Estados Unidos a apuestas ilegales o a otra actividad ilegal parecida (prostitución, contrabando, etc.)?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line33_yesno', N: 'pt8line33_yesno_1' },
      },
      {
        key: 'v_p9_34',
        type: 'radio',
        labelEs:
          '¿Alguna vez usaste inmunidad (diplomática u otra) para evitar que te procesaran por un delito en Estados Unidos?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line34_yesno_1', N: 'pt8line34_yesno' },
      },
      {
        key: 'v_p9_35a',
        type: 'radio',
        labelEs: '¿Alguna vez has trabajado como funcionario de un gobierno extranjero?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line35a_yesno', N: 'pt8line35a_yesno_1' },
      },
      {
        key: 'v_p9_35b',
        type: 'radio',
        labelEs:
          'Si respondiste Sí arriba: ¿alguna vez fuiste responsable de violaciones a la libertad religiosa, o las llevaste a cabo?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        dependsOn: { key: 'v_p9_35a', equals: 'Y' },
        real: { Y: 'pt8line35b_yesno_1', N: 'pt8line35b_yesno' },
      },
      {
        key: 'v_p9_36',
        type: 'radio',
        labelEs:
          '¿Alguna vez has obligado a otra persona, con fuerza o engaño, a realizar actos sexuales a cambio de dinero (trata sexual)?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line36_yesno_1', N: 'pt8line36_yesno' },
      },
      {
        key: 'v_p9_37',
        type: 'radio',
        labelEs:
          '¿Alguna vez has sometido a una persona a servidumbre, trabajo forzado, esclavitud o servidumbre por deudas (trata de personas)?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line37_yesno_1', N: 'pt8line37_yesno' },
      },
      {
        key: 'v_p9_38',
        type: 'radio',
        labelEs: '¿Alguna vez has ayudado a otras personas a cometer trata sexual o trata de personas para trabajo forzado?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line38_yesno', N: 'pt8line38_yesno_1' },
      },
      {
        key: 'v_p9_39',
        type: 'radio',
        labelEs:
          '¿Eres esposo(a), hijo o hija de alguien que se dedicó a la trata de personas, y recibiste algún beneficio de esa actividad en los últimos cinco años?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt9line39_yesno_1', N: 'pt9line39_yesno' },
      },
      {
        key: 'v_p9_40',
        type: 'radio',
        labelEs: 'Si respondiste Sí arriba: ¿sabías (o debías saber) que ese beneficio venía de esa actividad?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        dependsOn: { key: 'v_p9_39', equals: 'Y' },
        real: { Y: 'pt8line40_yesno_1', N: 'pt8line40_yesno' },
      },
      {
        key: 'v_p9_41',
        type: 'radio',
        labelEs: '¿Alguna vez te has dedicado al lavado de dinero, o has ayudado a alguien a hacerlo?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'delitos',
        real: { Y: 'pt8line41_yesno', N: 'pt8line41_yesno_1' },
      },
    ],
  },

  // ── 22. Seguridad ──────────────────────────────────────────────────────
  {
    id: 22,
    titleEs: 'Seguridad',
    descriptionEs:
      'Estas preguntas son sobre terrorismo, armas, grupos armados, persecución y temas de seguridad. La mayoría de las personas responde No a todo esto. Si alguna te genera duda, déjala en No y coméntala con tu asesora Vanessa.',
    fields: [
      {
        key: 'v_p9_42a',
        type: 'radio',
        labelEs: '¿Piensas hacer en Estados Unidos algo relacionado con espionaje o sabotaje?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'a_yesno', N: 'a_yesno_1' },
      },
      {
        key: 'v_p9_42b',
        type: 'radio',
        labelEs:
          '¿Piensas hacer en Estados Unidos algo que viole las leyes sobre exportar bienes, tecnología o información sensible?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'b_yesno_1', N: 'b_yesno' },
      },
      {
        key: 'v_p9_42c',
        type: 'radio',
        labelEs:
          '¿Piensas hacer algo cuyo fin sea oponerte, controlar o derrocar al gobierno de Estados Unidos por la fuerza o la violencia?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line42c_yesno_1', N: 'pt8line42c_yesno' },
      },
      {
        key: 'v_p9_42d',
        type: 'radio',
        labelEs: '¿Piensas dedicarte a cualquier otra actividad ilegal?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line42d_yesno', N: 'pt8line42d_yesno_1' },
      },
      {
        key: 'v_p9_43a',
        type: 'radio',
        labelEs: '¿Alguna vez has recibido entrenamiento con armas, entrenamiento paramilitar o de tipo militar?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line43a_yesno_1', N: 'pt8line43a_yesno' },
      },
      {
        key: 'v_p9_43b',
        type: 'radio',
        labelEs: '¿Alguna vez has cometido un secuestro, un asesinato, o el secuestro o sabotaje de un avión, barco, vehículo o tren?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line43b_yesno', N: 'pt8line43b_yesno_1' },
      },
      {
        key: 'v_p9_43c',
        type: 'radio',
        labelEs:
          '¿Alguna vez has usado un arma o un explosivo con la intención de poner en peligro a otras personas o dañar propiedad?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line43c_yesno', N: 'pt8line43c_yesno_1' },
      },
      {
        key: 'v_p9_43d',
        type: 'radio',
        labelEs: '¿Alguna vez has amenazado, intentado o planeado hacer alguna de las cosas descritas arriba?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line43d_yesno', N: 'pt8line43d_yesno_1' },
      },
      {
        key: 'v_p9_43e',
        type: 'radio',
        labelEs: '¿Alguna vez has incitado a otros a hacer alguna de esas cosas, con la intención de causar muerte o daño grave?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line43e_yesno', N: 'pt8line43e_yesno_1' },
      },
      {
        key: 'v_p9_43f',
        type: 'radio',
        labelEs: '¿Alguna vez has participado o sido miembro de un grupo u organización que hizo alguna de esas cosas?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line43fyesno', N: 'pt8line43fyesno_1' },
      },
      {
        key: 'v_p9_43g',
        type: 'radio',
        labelEs: '¿Alguna vez has reclutado miembros o pedido dinero para un grupo que hizo alguna de esas cosas?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line43g_yesno', N: 'pt8line43g_yesno_1' },
      },
      {
        key: 'v_p9_43h',
        type: 'radio',
        labelEs: '¿Alguna vez has dado dinero, servicios o cualquier otro apoyo a un grupo que hizo alguna de esas cosas?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line43h_yesno_1', N: 'pt8line43h_yesno' },
      },
      {
        key: 'v_p9_43i',
        type: 'radio',
        labelEs: '¿Alguna vez has dado dinero, servicios o cualquier otro apoyo a una persona o grupo que hizo alguna de esas cosas?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line43i_yesno_1', N: 'pt8line43i_yesno' },
      },
      {
        key: 'v_p9_44',
        type: 'radio',
        labelEs: '¿Piensas dedicarte a alguna de las actividades descritas arriba?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line44_yesno', N: 'pt8line44_yesno_1' },
      },
      {
        key: 'v_p9_45',
        type: 'radio',
        labelEs: '¿Piensas dedicarte a alguna actividad que pueda poner en peligro la seguridad de Estados Unidos?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line45_yesno_1', N: 'pt8line45_yesno' },
      },
      {
        key: 'v_p9_46',
        type: 'radio',
        labelEs: '¿Eres esposo(a) o hijo(a) de alguien que haya hecho alguna de las actividades descritas arriba?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line46_yesno', N: 'pt8line46_yesno_1' },
      },
      {
        key: 'v_p9_47',
        type: 'radio',
        labelEs:
          '¿Alguna vez has vendido, dado o transportado armas (o ayudado a alguien a hacerlo) sabiendo que se usarían contra otra persona?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line47_yesno_1', N: 'pt8line47_yesno' },
      },
      {
        key: 'v_p9_48',
        type: 'radio',
        labelEs:
          '¿Alguna vez has trabajado o servido en una cárcel, campo de detención o cualquier lugar donde se detenía a personas, o participado en detener personas?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line48_yesno_1', N: 'pt8line48_yesno' },
      },
      {
        key: 'v_p9_49',
        type: 'radio',
        labelEs:
          '¿Alguna vez has sido miembro de un grupo en el que tú u otras personas usaron armas contra alguien, o amenazaron con hacerlo?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line49_yesno', N: 'pt8line49_yesno_1' },
      },
      {
        key: 'v_p9_50',
        type: 'radio',
        labelEs: '¿Alguna vez has servido o sido miembro de alguna unidad militar o policial?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line50_yesno_1', N: 'pt8line50_yesno' },
      },
      {
        key: 'v_p9_51',
        type: 'radio',
        labelEs:
          '¿Alguna vez has servido o sido miembro de algún grupo armado, como un grupo paramilitar, de autodefensa, vigilante, rebelde o guerrillero?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line51_yesno', N: 'pt8line51_yesno_1' },
      },
      {
        key: 'v_p9_52',
        type: 'radio',
        labelEs:
          '¿Alguna vez has sido miembro del Partido Comunista o de cualquier otro partido totalitario, en Estados Unidos o en otro país?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line52_yesno_1', N: 'pt8line52_yesno' },
      },
      {
        key: 'v_p9_53a',
        type: 'radio',
        labelEs: '¿Alguna vez has ordenado, cometido o participado en tortura?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line53a_yesno', N: 'pt8line53a_yesno_1' },
      },
      {
        key: 'v_p9_53b',
        type: 'radio',
        labelEs: '¿Alguna vez has ordenado, cometido o participado en genocidio?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line53b_yesno', N: 'pt8line53b_yesno_1' },
      },
      {
        key: 'v_p9_53c',
        type: 'radio',
        labelEs: '¿Alguna vez has matado o intentado matar a alguna persona?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line53c_yesno', N: 'pt8line53c_yesno_1' },
      },
      {
        key: 'v_p9_53d',
        type: 'radio',
        labelEs: '¿Alguna vez has herido gravemente o intentado herir gravemente a alguna persona, a propósito?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line53d_yesno_1', N: 'pt8line53d_yesno' },
      },
      {
        key: 'v_p9_54',
        type: 'radio',
        labelEs:
          '¿Alguna vez has reclutado o usado a un menor de 15 años para participar en combate o servir en un grupo armado?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line54_yesno_1', N: 'pt8line54_yesno' },
      },
      {
        key: 'v_p9_55',
        type: 'radio',
        labelEs: '¿Alguna vez has usado a un menor de 15 años para participar en hostilidades o tareas de combate?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'seguridad',
        real: { Y: 'pt8line55_yesno', N: 'pt8line55_yesno_1' },
      },
    ],
  },

  // ── 23. Entradas y faltas migratorias ──────────────────────────────────
  {
    id: 23,
    titleEs: 'Entradas y faltas migratorias',
    descriptionEs:
      'Estas preguntas son sobre entradas al país y documentos. La mayoría de las personas responde No a todo esto. Si alguna te genera duda, déjala en No y coméntala con tu asesora Vanessa.',
    fields: [
      {
        key: 'v_p9_67',
        type: 'radio',
        labelEs: '¿Alguna vez faltaste o te negaste a presentarte a una audiencia de remoción presentada en tu contra (desde el 1 de abril de 1997)?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'entradas',
        real: { Y: 'pt9line67_yesno_1', N: 'pt9line67_yesno' },
      },
      {
        key: 'v_p9_68',
        type: 'radio',
        labelEs:
          '¿Alguna vez has presentado documentos alterados, falsos o falsificados a un oficial del gobierno de Estados Unidos para obtener un beneficio migratorio?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'entradas',
        real: { Y: 'pt9line68_yesno', N: 'pt9line68_yesno_1' },
      },
      {
        key: 'v_p9_69',
        type: 'radio',
        labelEs:
          '¿Alguna vez has mentido, ocultado o falseado información en una solicitud para obtener una visa, entrada a Estados Unidos o cualquier beneficio migratorio?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'entradas',
        real: { Y: 'pt9line69_yesno_1', N: 'pt9line69_yesno' },
      },
      {
        key: 'v_p9_70',
        type: 'radio',
        labelEs: '¿Alguna vez has dicho falsamente que eres ciudadano de Estados Unidos (por escrito o de cualquier otra forma)?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'entradas',
        real: { Y: 'pt9line70_yesno', N: 'pt9line70_yesno_1' },
      },
      {
        key: 'v_p9_71',
        type: 'radio',
        labelEs: '¿Alguna vez has sido polizón en un barco o avión que llegaba a Estados Unidos?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'entradas',
        real: { Y: 'pt9line71_yesno_1', N: 'pt9line71_yesno' },
      },
      {
        key: 'v_p9_72',
        type: 'radio',
        labelEs:
          '¿Alguna vez has ayudado a otra persona a entrar o intentar entrar ilegalmente a Estados Unidos (contrabando de personas)?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'entradas',
        real: { Y: 'pt9line72_yesno', N: 'pt9line72_yesno_1' },
      },
      {
        key: 'v_p9_73',
        type: 'radio',
        labelEs: '¿Tienes una orden final de multa civil por usar documentos fraudulentos?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'entradas',
        real: { Y: 'pt9line73_yesno_1', N: 'pt9line73_yesno' },
      },
    ],
  },

  // ── 24. Deportaciones previas ──────────────────────────────────────────
  {
    id: 24,
    titleEs: 'Deportaciones previas',
    descriptionEs:
      'Estas preguntas son sobre deportaciones, tiempo sin permiso en el país y reingresos. La mayoría de las personas responde No a todo esto. Si alguna te genera duda, déjala en No y coméntala con tu asesora Vanessa.',
    fields: [
      {
        key: 'v_p9_74',
        type: 'radio',
        labelEs:
          '¿Alguna vez te han deportado o removido de Estados Unidos, o saliste por tu cuenta después de que te ordenaran salir?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'deportaciones',
        real: { Y: 'pt9line74_yesno_1', N: 'pt9line74_yesno' },
      },
      {
        key: 'v_p9_75',
        type: 'radio',
        labelEs: '¿Alguna vez entraste a Estados Unidos sin ser inspeccionado y admitido, o sin permiso (parole)?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'deportaciones',
        real: { Y: 'pt9line75_yesno', N: 'pt9line75_yesno_1' },
      },
      {
        key: 'v_p9_76',
        type: 'radio',
        labelEs:
          'Desde el 1 de abril de 1997, ¿has estado en Estados Unidos sin permiso (después de que se venciera tu estadía autorizada, o sin haber sido admitido)?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'deportaciones',
        real: { Y: 'pt9line76_yesno_1', N: 'pt9line76_yesno' },
      },
      {
        key: 'v_p9_77',
        type: 'radio',
        labelEs:
          'Si respondiste Sí arriba: ¿una de las razones principales de tu estadía sin permiso fue ser víctima de trata de personas?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'deportaciones',
        dependsOn: { key: 'v_p9_76', equals: 'Y' },
        real: { Y: 'pt9line77_yesno', N: 'pt9line77_yesno_1' },
      },
      {
        key: 'v_p9_78a',
        type: 'radio',
        labelEs:
          'Desde el 1 de abril de 1997, ¿volviste a entrar (o intentaste entrar) sin permiso después de haber estado sin permiso por más de un año en total?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'deportaciones',
        real: { Y: 'pt9line78a_yesno_1', N: 'pt9line78a_yesno' },
      },
      {
        key: 'v_p9_78b',
        type: 'radio',
        labelEs: 'Desde el 1 de abril de 1997, ¿volviste a entrar (o intentaste entrar) sin permiso después de haber sido deportado o removido?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'deportaciones',
        real: { Y: 'pt9line78b_yesno', N: 'pt9line78b_yesno_1' },
      },
    ],
  },

  // ── 25. Otras conductas ────────────────────────────────────────────────
  {
    id: 25,
    titleEs: 'Otras conductas',
    descriptionEs:
      'Estas son las últimas preguntas: poligamia, votar de forma ilegal, renunciar a la ciudadanía y el servicio militar. La mayoría de las personas responde No a todo esto. Si alguna te genera duda, déjala en No y coméntala con tu asesora Vanessa.',
    fields: [
      {
        key: 'v_p9_79',
        type: 'radio',
        labelEs: '¿Piensas practicar la poligamia (tener más de un esposo o esposa al mismo tiempo) en Estados Unidos?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'otras',
        real: { Y: 'pt9line79_yesno', N: 'pt9line79_yesno_1' },
      },
      {
        key: 'v_p9_80',
        type: 'radio',
        labelEs:
          '¿Vienes acompañando a una persona que no puede entrar por sí sola (por enfermedad, discapacidad o por ser un bebé) y que necesita tu cuidado?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'otras',
        real: { Y: 'pt9line80_yesno_1', N: 'pt9line80_yesno' },
      },
      {
        key: 'v_p9_81',
        type: 'radio',
        labelEs:
          '¿Alguna vez ayudaste a retener fuera de Estados Unidos a un niño ciudadano estadounidense, lejos de la persona que tenía su custodia?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'otras',
        real: { Y: 'pt9line81_yesno', N: 'pt9line81_yesno_1' },
      },
      {
        key: 'v_p9_82',
        type: 'radio',
        labelEs: '¿Alguna vez has votado en Estados Unidos violando alguna ley (por ejemplo, sin tener derecho a votar)?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'otras',
        real: { Y: 'pt9line82_yesno_1', N: 'pt9line82_yesno' },
      },
      {
        key: 'v_p9_83',
        type: 'radio',
        labelEs: '¿Alguna vez renunciaste a la ciudadanía de Estados Unidos para evitar pagar impuestos?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'otras',
        real: { Y: 'pt9line83_yesno', N: 'pt9line83_yesno_1' },
      },
      {
        key: 'v_p9_84a',
        type: 'radio',
        labelEs:
          '¿Alguna vez pediste que te eximieran del servicio militar de Estados Unidos por el hecho de ser extranjero?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'otras',
        real: { Y: 'pt9line84a_yesno_1', N: 'pt9line84a_yesno' },
      },
      {
        key: 'v_p9_84b',
        type: 'radio',
        labelEs: '¿Alguna vez te eximieron o liberaron del servicio militar de Estados Unidos por ser extranjero?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'otras',
        real: { Y: 'pt9line84b_yesno_1', N: 'pt9line84b_yesno' },
      },
      {
        key: 'v_p9_84c',
        type: 'radio',
        labelEs: '¿Alguna vez te condenaron por desertar de las fuerzas armadas de Estados Unidos?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'otras',
        real: { Y: 'pt9line84c_yesno_1', N: 'pt9line84c_yesno' },
      },
      {
        key: 'v_p9_85a',
        type: 'radio',
        labelEs:
          '¿Alguna vez saliste o te quedaste fuera de Estados Unidos para evitar el servicio militar en tiempo de guerra o de emergencia nacional?',
        options: [{ value: 'Y', labelEs: 'Sí' }, { value: 'N', labelEs: 'No' }],
        required: true,
        groupKey: 'otras',
        real: { Y: 'pt9line85_yesno_1', N: 'pt9line85_yesno' },
      },
      {
        key: 'pt9line86_nationality',
        type: 'text',
        labelEs: 'Si respondiste Sí arriba: ¿cuál era tu nacionalidad o estatus migratorio justo antes de salir?',
        helpEs: 'Solo si respondiste Sí a la pregunta anterior.',
        groupKey: 'otras',
        dependsOn: { key: 'v_p9_85a', equals: 'Y' },
      },
    ],
  }
]
