import type { ServiceWorkflow, WorkflowStep } from '@/types/wizard'

/**
 * Workflow del servicio "Asilo Político" con 2 fases operativas:
 *
 * - Fase 1 (asilo_sustentos): cliente sube documentos de identidad y entrada,
 *   y llena las partes 1-5 del I-589 (steps 1-5 abajo).
 * - Fase 2 (asilo_reforzar): cliente sube affidavit personal + URLs de
 *   evidencias; Diana + IA generan el Miedo Creíble y completan partes 6-14
 *   del I-589. Eso pasa fuera del wizard tradicional — vive en
 *   `/cita/[token]` screen "Reforzar Asilo" y panel Diana.
 *
 * Reemplaza los workflows legacy `asilo-afirmativo` y `asilo-defensivo`
 * (eliminados en el mismo PR-3 que introduce este archivo).
 */

export const asiloPoliticoSteps: WorkflowStep[] = [
  {
    step: 1,
    title: 'Información Personal',
    description: 'Parte 1 del I-589 — Datos personales del solicitante',
    type: 'form',
    fields: [
      { key: 'legal_last_name', label: 'Apellido legal', type: 'text', required: true },
      { key: 'legal_first_name', label: 'Nombre legal', type: 'text', required: true },
      { key: 'legal_middle_name', label: 'Segundo nombre', type: 'text' },
      {
        key: 'other_names',
        label: 'Otros nombres usados',
        type: 'text_array',
        helper: 'Incluya nombres de soltera, alias, o cualquier otro nombre usado',
      },
      { key: 'residence_address_street', label: 'Dirección de residencia (calle)', type: 'text', required: true },
      { key: 'residence_address_city', label: 'Ciudad', type: 'text', required: true },
      { key: 'residence_address_state', label: 'Estado', type: 'us_state_select', required: true },
      { key: 'residence_address_zip', label: 'Código postal', type: 'text', required: true },
      { key: 'residence_phone', label: 'Teléfono', type: 'phone', required: true },
      {
        key: 'mailing_same_as_residence',
        label: '¿La dirección postal es la misma que la de residencia?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'mailing_address',
        label: 'Dirección postal',
        type: 'address_group',
        conditional: 'mailing_same_as_residence === false',
      },
      {
        key: 'gender',
        label: 'Sexo',
        type: 'select',
        options: ['Masculino', 'Femenino'],
        required: true,
        helper: 'El formulario I-589 solo permite Masculino o Femenino',
      },
      {
        key: 'marital_status',
        label: 'Estado civil',
        type: 'select',
        options: ['Soltero/a', 'Casado/a', 'Divorciado/a', 'Viudo/a'],
        required: true,
      },
      { key: 'date_of_birth', label: 'Fecha de nacimiento', type: 'date', required: true },
      { key: 'city_of_birth', label: 'Ciudad de nacimiento', type: 'text', required: true },
      { key: 'country_of_birth', label: 'País de nacimiento', type: 'country_select', required: true },
      { key: 'nationality', label: 'Nacionalidad', type: 'country_select', required: true },
      { key: 'race_ethnicity', label: 'Raza / Etnicidad', type: 'text' },
      { key: 'religion', label: 'Religión', type: 'text' },
      { key: 'native_language', label: 'Idioma nativo', type: 'text', required: true },
      { key: 'speaks_english', label: '¿Habla inglés con fluidez?', type: 'boolean', required: true },
      { key: 'other_languages', label: 'Otros idiomas que habla', type: 'text' },
    ],
  },
  {
    step: 2,
    title: 'Información de Inmigración',
    description: 'Parte 2 del I-589 — Historial migratorio y documentos de viaje',
    type: 'form',
    fields: [
      {
        key: 'immigration_court_proceedings',
        label: '¿Está actualmente en proceso ante un tribunal de inmigración?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'last_entry_date',
        label: 'Fecha de última entrada a EE.UU.',
        type: 'date',
        required: true,
        helper: 'CRÍTICA — debe aplicar dentro de 1 año de su última entrada',
      },
      { key: 'i94_number', label: 'Número I-94', type: 'text' },
      {
        key: 'entry_status',
        label: 'Estatus de entrada',
        type: 'select',
        options: [
          'Visa de turista (B-1/B-2)',
          'Visa de estudiante (F-1)',
          'Visa de trabajo',
          'Parole',
          'NTA (Notice to Appear)',
          'Sin inspección (cruzó la frontera)',
          'TPS',
          'Otro',
        ],
        required: true,
      },
      {
        key: 'entry_status_other',
        label: 'Especifique otro estatus de entrada',
        type: 'text',
        conditional: "entry_status === 'Otro'",
      },
      {
        key: 'entry_place',
        label: 'Lugar de entrada',
        type: 'text',
        required: true,
        helper: 'Puerto de entrada, aeropuerto, o punto de cruce',
      },
      { key: 'status_expires', label: 'Fecha de expiración del estatus', type: 'date' },
      { key: 'passport_number', label: 'Número de pasaporte', type: 'text', required: true },
      { key: 'passport_country', label: 'País del pasaporte', type: 'country_select', required: true },
      { key: 'passport_expiry', label: 'Fecha de expiración del pasaporte', type: 'date', required: true },
      { key: 'travel_document_number', label: 'Número de documento de viaje', type: 'text' },
      {
        key: 'a_number',
        label: 'Número A (Alien Number)',
        type: 'text',
        helper: "Comienza con 'A' seguido de 8 o 9 dígitos",
      },
      { key: 'ssn', label: 'Número de Seguro Social (SSN)', type: 'text' },
      { key: 'uscis_account', label: 'Número de cuenta USCIS', type: 'text' },
    ],
  },
  {
    step: 3,
    title: 'Cónyuge e Hijos',
    description: 'Parte 3 del I-589 — Información de familiares',
    type: 'form',
    fields: [
      { key: 'has_spouse', label: '¿Tiene cónyuge?', type: 'boolean', required: true },
      {
        key: 'spouse_info',
        label: 'Información del cónyuge',
        type: 'spouse_form',
        conditional: 'has_spouse === true',
        subfields: [
          { key: 'spouse_last_name', label: 'Apellido del cónyuge', type: 'text' },
          { key: 'spouse_first_name', label: 'Nombre del cónyuge', type: 'text' },
          { key: 'spouse_middle_name', label: 'Segundo nombre del cónyuge', type: 'text' },
          { key: 'spouse_other_names', label: 'Otros nombres del cónyuge', type: 'text' },
          { key: 'spouse_dob', label: 'Fecha de nacimiento', type: 'date' },
          {
            key: 'spouse_gender',
            label: 'Sexo del cónyuge',
            type: 'select',
            options: ['Masculino', 'Femenino'],
          },
          { key: 'spouse_nationality', label: 'Nacionalidad del cónyuge', type: 'country_select' },
          { key: 'spouse_a_number', label: 'Número A del cónyuge', type: 'text' },
          { key: 'spouse_ssn', label: 'SSN del cónyuge', type: 'text' },
          { key: 'spouse_in_us', label: '¿El cónyuge está en EE.UU.?', type: 'boolean' },
          {
            key: 'spouse_include_in_application',
            label: '¿Incluir cónyuge en la solicitud de asilo?',
            type: 'boolean',
          },
          { key: 'spouse_immigration_status', label: 'Estatus migratorio del cónyuge', type: 'text' },
          { key: 'marriage_date', label: 'Fecha de matrimonio', type: 'date' },
          { key: 'marriage_place', label: 'Lugar de matrimonio', type: 'text' },
        ],
      },
      { key: 'has_children', label: '¿Tiene hijos?', type: 'boolean', required: true },
      {
        key: 'children',
        label: 'Información de los hijos',
        type: 'repeatable_group',
        conditional: 'has_children === true',
        subfields: [
          { key: 'child_last_name', label: 'Apellido del hijo/a', type: 'text' },
          { key: 'child_first_name', label: 'Nombre del hijo/a', type: 'text' },
          { key: 'child_dob', label: 'Fecha de nacimiento', type: 'date' },
          {
            key: 'child_gender',
            label: 'Sexo',
            type: 'select',
            options: ['Masculino', 'Femenino'],
          },
          { key: 'child_country_of_birth', label: 'País de nacimiento', type: 'country_select' },
          { key: 'child_nationality', label: 'Nacionalidad', type: 'country_select' },
          { key: 'child_a_number', label: 'Número A del hijo/a', type: 'text' },
          { key: 'child_in_us', label: '¿El hijo/a está en EE.UU.?', type: 'boolean' },
          {
            key: 'child_include_in_application',
            label: '¿Incluir en la solicitud de asilo?',
            type: 'boolean',
          },
          {
            key: 'child_marital_status',
            label: '¿El hijo/a es soltero/a y menor de 21?',
            type: 'boolean',
            helper: 'Debe ser soltero/a y menor de 21 para ser incluido en la solicitud',
          },
        ],
      },
    ],
  },
  {
    step: 4,
    title: 'Historial de Residencia y Empleo',
    description: 'Parte 4 del I-589 — Direcciones, empleos, educación y familiares (últimos 5 años)',
    type: 'form',
    fields: [
      {
        key: 'last_address_before_us',
        label: 'Última dirección antes de venir a EE.UU.',
        type: 'address_group',
        helper: 'La dirección donde vivía en su país antes de llegar a Estados Unidos',
        subfields: [
          { key: 'street', label: 'Calle', type: 'text' },
          { key: 'city', label: 'Ciudad', type: 'text' },
          { key: 'state', label: 'Departamento / Estado / Provincia', type: 'text' },
          { key: 'country', label: 'País', type: 'country_select' },
          { key: 'from', label: 'Desde', type: 'month_year' },
          { key: 'to', label: 'Hasta', type: 'month_year_or_present' },
        ],
      },
      {
        key: 'residences_last_5_years',
        label: 'Residencias en los últimos 5 años',
        type: 'repeatable_group',
        helper: 'Empezando por la más reciente',
        subfields: [
          { key: 'res_address', label: 'Dirección', type: 'text' },
          { key: 'res_city', label: 'Ciudad', type: 'text' },
          { key: 'res_country', label: 'País', type: 'country_select' },
          { key: 'res_from', label: 'Desde', type: 'month_year' },
          { key: 'res_to', label: 'Hasta', type: 'month_year_or_present' },
        ],
      },
      {
        key: 'employment_last_5_years',
        label: 'Empleos en los últimos 5 años',
        type: 'repeatable_group',
        helper: 'Incluya en su país y en EE.UU.',
        subfields: [
          { key: 'emp_employer', label: 'Empleador', type: 'text' },
          { key: 'emp_address', label: 'Dirección', type: 'text' },
          { key: 'emp_occupation', label: 'Ocupación', type: 'text' },
          { key: 'emp_from', label: 'Desde', type: 'month_year' },
          { key: 'emp_to', label: 'Hasta', type: 'month_year_or_present' },
        ],
      },
      {
        key: 'education',
        label: 'Educación',
        type: 'repeatable_group',
        subfields: [
          { key: 'edu_school', label: 'Escuela o institución', type: 'text' },
          { key: 'edu_type', label: 'Tipo de estudio', type: 'text' },
          { key: 'edu_location', label: 'Ubicación', type: 'text' },
          { key: 'edu_from', label: 'Desde', type: 'month_year' },
          { key: 'edu_to', label: 'Hasta', type: 'month_year_or_present' },
        ],
      },
      { key: 'mother_name', label: 'Nombre completo de la madre (Apellido Nombre)', type: 'text' },
      { key: 'mother_country_of_birth', label: 'País de nacimiento de la madre', type: 'country_select' },
      { key: 'mother_deceased', label: '¿La madre ha fallecido?', type: 'boolean' },
      { key: 'mother_current_location', label: 'Ubicación actual de la madre', type: 'text', conditional: 'mother_deceased === false' },
      { key: 'father_name', label: 'Nombre completo del padre (Apellido Nombre)', type: 'text' },
      { key: 'father_country_of_birth', label: 'País de nacimiento del padre', type: 'country_select' },
      { key: 'father_deceased', label: '¿El padre ha fallecido?', type: 'boolean' },
      { key: 'father_current_location', label: 'Ubicación actual del padre', type: 'text', conditional: 'father_deceased === false' },
      {
        key: 'siblings',
        label: 'Hermanos/as',
        type: 'repeatable_group',
        helper: 'Incluya todos sus hermanos y hermanas',
        subfields: [
          { key: 'sibling_name', label: 'Nombre completo (Apellido Nombre)', type: 'text' },
          { key: 'sibling_country_of_birth', label: 'País de nacimiento', type: 'country_select' },
          { key: 'sibling_deceased', label: '¿Ha fallecido?', type: 'boolean' },
          { key: 'sibling_current_location', label: 'Ubicación actual', type: 'text' },
        ],
      },
    ],
  },
  {
    step: 5,
    title: 'Información Preliminar de Persecución',
    description: 'Parte 5 del I-589 — Bases preliminares (el detalle completo viene en Fase 2)',
    type: 'form',
    fields: [
      {
        key: 'persecution_grounds',
        label: 'Bases de persecución',
        type: 'multi_select',
        options: [
          'Raza',
          'Religión',
          'Nacionalidad',
          'Opinión política',
          'Pertenencia a un grupo social particular',
        ],
        required: true,
      },
      {
        key: 'past_harm',
        label: '¿Ha sufrido daño o persecución en el pasado?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'fear_of_return',
        label: '¿Tiene miedo de regresar a su país?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'reported_to_authorities',
        label: '¿Reportó los hechos a las autoridades?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'prior_asylum_application',
        label: '¿Ha solicitado asilo anteriormente en EE.UU.?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'arrested_detained',
        label: '¿Ha sido arrestado, detenido o encarcelado?',
        type: 'boolean',
        required: true,
      },
    ],
  },
  {
    step: 6,
    title: 'Documentos de Soporte',
    description: 'Suba los documentos de Fase 1: identidad, estatus de ingreso y (si aplica) acta matrimonial',
    type: 'documents',
  },
]

export const asiloPoliticoWorkflow: ServiceWorkflow = {
  slug: 'asilo-politico',
  name: 'Asilo Político',
  steps: asiloPoliticoSteps,
  required_documents: [
    { key: 'passport', label: 'Pasaporte', required: true, category: 'identidad' },
    { key: 'photo_id', label: 'Cédula o identificación con foto', required: true, category: 'identidad' },
    { key: 'i94', label: 'Registro I-94 (si entró por avión)', required: false, category: 'inmigración' },
    {
      key: 'parole_nta',
      label: 'Parole / NTA (Notice to Appear)',
      required: false,
      category: 'inmigración',
      helper: 'Documento oficial de entrada o aviso a corte',
    },
    {
      key: 'marriage_certificate',
      label: 'Acta de matrimonio',
      required: false,
      category: 'familia',
      helper: 'Obligatorio si aplica como Familiar Casados',
    },
    {
      key: 'children_birth_certificates',
      label: 'Actas de nacimiento de hijos',
      required: false,
      category: 'familia',
      multiple: true,
      helper: 'Con ambos apellidos para convivientes con hijos en común',
    },
    {
      key: 'personal_affidavit',
      label: 'Declaración jurada personal (DOCX o PDF)',
      required: false,
      category: 'caso',
      helper: 'Se sube en Fase 2 — alimenta el generador de Miedo Creíble',
    },
    {
      key: 'evidence_persecution',
      label: 'Evidencias de persecución',
      required: false,
      category: 'caso',
      multiple: true,
      helper: 'Fotos, reportes policiales, amenazas, etc.',
    },
    {
      key: 'country_conditions',
      label: 'Condiciones del país de origen',
      required: false,
      category: 'caso',
      multiple: true,
    },
  ],
  eligibility_questions: [
    {
      id: 'in_us',
      question: '¿Se encuentra actualmente en Estados Unidos?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'Debe encontrarse físicamente en EE.UU. para solicitar asilo.',
    },
    {
      id: 'arrival_within_year',
      question: '¿Llegó a EE.UU. hace menos de 1 año?',
      type: 'boolean',
      required_answer: true,
      fail_message:
        'Generalmente debe solicitar asilo dentro de 1 año de su llegada. Existen excepciones — Henry puede evaluar su caso.',
    },
    {
      id: 'persecution_basis',
      question: '¿Cuál es la base de su temor de persecución?',
      type: 'multi_select',
      options: [
        'Raza',
        'Religión',
        'Nacionalidad',
        'Opinión política',
        'Pertenencia a un grupo social particular',
      ],
      min_selections: 1,
      fail_message: 'El asilo requiere al menos una base protegida de persecución.',
    },
  ],
}
