-- ══════════════════════════════════════════════════════════════════
-- SEED de document_types (60 documentos SIJS)
--
-- Fuente: usalatino-sijs-documentos-dinamicos.md sección 7 (Matriz
-- de visibilidad). Categorías humanas según recomendación UX
-- sección 9 del mismo doc.
--
-- conditional_logic JSONB shape:
--   { "type": "flag_eq", "flag": "parent_deceased", "value": true }
-- Evaluado server-side contra cases.<flag> para mostrar/ocultar.
-- ══════════════════════════════════════════════════════════════════

INSERT INTO public.document_types
  (code, name_es, name_en, description_es, category_code, category_name_es, category_icon,
   requires_translation, requires_certified_copy, shown_in_custodia, shown_in_i360, shown_in_i485,
   conditional_logic, slot_kind, max_slots, sort_order, legal_reference)
VALUES

-- ─── Sobre el menor (identidad) ───
('minor_birth_certificate',
 'Acta de nacimiento del menor',
 'Minor Birth Certificate',
 'Apostillada idealmente. Original + traducción certificada al inglés.',
 'sobre_el_menor', 'Sobre el menor', 'child_care',
 true, true, true, true, true,
 NULL, 'dual_es_en', NULL, 10, '8 CFR §204.11(c)'),

('minor_passport',
 'Pasaporte del menor',
 'Minor Passport',
 'Vigente o vencido. Todas las páginas con sellos.',
 'sobre_el_menor', 'Sobre el menor', 'child_care',
 true, false, true, true, true,
 NULL, 'dual_es_en', NULL, 20, NULL),

('minor_national_id',
 'DNI / cédula del país de origen',
 'National ID / Country ID',
 'Documento nacional de identidad del país de origen, si existe.',
 'sobre_el_menor', 'Sobre el menor', 'child_care',
 true, false, true, true, false,
 NULL, 'dual_es_en', NULL, 30, NULL),

('minor_passport_photo',
 'Foto pasaporte reciente del menor',
 'Recent Passport Photo of Minor',
 'Para identificación en corte y trámites USCIS.',
 'sobre_el_menor', 'Sobre el menor', 'child_care',
 false, false, true, true, true,
 NULL, 'single', NULL, 40, NULL),

('minor_i94',
 'Form I-94',
 'Form I-94',
 'Registro de entrada/salida si entró por puerto oficial.',
 'sobre_el_menor', 'Sobre el menor', 'child_care',
 false, false, true, true, true,
 NULL, 'single', NULL, 50, NULL),

('minor_cbp_stamp',
 'Sello de admisión / parole de CBP',
 'CBP Admission/Parole Stamp',
 'En el pasaporte, si aplica.',
 'sobre_el_menor', 'Sobre el menor', 'child_care',
 false, false, true, true, true,
 NULL, 'single', NULL, 60, NULL),

-- ─── Sobre el custodio y mi hogar ───
('custodian_photo_id',
 'Identificación con foto del custodio',
 'Custodian Photo ID',
 'Driver''s License, State ID o pasaporte vigente.',
 'sobre_el_custodio', 'Sobre el custodio y mi hogar', 'home',
 false, false, true, false, false,
 NULL, 'single', NULL, 70, NULL),

('custodian_immigration_status',
 'Comprobante de estatus migratorio del custodio',
 'Custodian Immigration Status Proof',
 'Green card, ciudadanía, visa o EAD si aplica.',
 'sobre_el_custodio', 'Sobre el custodio y mi hogar', 'home',
 false, false, true, false, false,
 NULL, 'single', NULL, 80, NULL),

('home_lease',
 'Contrato de arrendamiento (lease)',
 'Lease Agreement',
 'Con nombre del custodio y dirección actual.',
 'sobre_el_custodio', 'Sobre el custodio y mi hogar', 'home',
 false, false, true, false, false,
 NULL, 'single', NULL, 90, NULL),

('home_utility_bills',
 'Recibos de servicios públicos',
 'Utility Bills',
 'Últimos 2-3 meses (luz, agua, gas, internet) al nombre del custodio.',
 'sobre_el_custodio', 'Sobre el custodio y mi hogar', 'home',
 false, false, true, false, false,
 NULL, 'multiple_named', 5, 100, NULL),

('custodian_income_proof',
 'Comprobante de ingresos del custodio',
 'Custodian Income Proof',
 'Pay stubs últimos 2 meses, W-2 o tax returns. Demuestra capacidad financiera.',
 'sobre_el_custodio', 'Sobre el custodio y mi hogar', 'home',
 false, false, true, false, false,
 NULL, 'multiple_named', 5, 110, NULL),

('custodian_background_check',
 'Antecedentes penales del custodio',
 'Custodian Background Check',
 'Background check o police clearance. Requerido por la mayoría de cortes estatales.',
 'sobre_el_custodio', 'Sobre el custodio y mi hogar', 'home',
 false, false, true, false, false,
 NULL, 'single', NULL, 120, NULL),

('custodian_birth_certificate',
 'Acta de nacimiento del custodio',
 'Custodian Birth Certificate',
 'Si es familiar — para probar parentesco con el menor.',
 'sobre_el_custodio', 'Sobre el custodio y mi hogar', 'home',
 true, false, true, false, false,
 NULL, 'dual_es_en', NULL, 130, NULL),

('custodian_marriage_certificate',
 'Acta de matrimonio del custodio',
 'Custodian Marriage Certificate',
 'Si el custodio es casado. Algunos estados requieren consentimiento del cónyuge.',
 'sobre_el_custodio', 'Sobre el custodio y mi hogar', 'home',
 true, false, true, false, false,
 NULL, 'dual_es_en', NULL, 140, NULL),

-- ─── Sobre mi familia ───
('parents_marriage_certificate',
 'Acta de matrimonio de los padres del menor',
 'Parents Marriage Certificate',
 'Si están o estuvieron casados.',
 'sobre_la_familia', 'Sobre mi familia', 'family_restroom',
 true, false, true, true, false,
 NULL, 'dual_es_en', NULL, 150, NULL),

('parents_divorce_certificate',
 'Acta de divorcio de los padres',
 'Parents Divorce Certificate',
 'Si aplica.',
 'sobre_la_familia', 'Sobre mi familia', 'family_restroom',
 true, false, true, true, false,
 NULL, 'dual_es_en', NULL, 160, NULL),

('parent_death_certificate',
 'Acta de defunción del padre o madre',
 'Parent Death Certificate',
 'Crítico si hay fallecimiento — sustenta abandono en muchos estados.',
 'sobre_la_familia', 'Sobre mi familia', 'family_restroom',
 true, true, true, true, false,
 '{"type":"flag_eq","flag":"parent_deceased","value":true}'::jsonb,
 'dual_es_en', NULL, 170, '8 CFR §204.11(c)(1)(ii)'),

('relation_documents',
 'Documentos de parentesco menor ↔ custodio',
 'Relationship Documents (Minor ↔ Custodian)',
 'Actas de nacimiento que conecten el árbol genealógico.',
 'sobre_la_familia', 'Sobre mi familia', 'family_restroom',
 true, false, true, false, false,
 NULL, 'multiple_named', 10, 180, NULL),

-- ─── Evidencia de mi situación (abuso / abandono / negligencia) ───
('minor_affidavit',
 'Declaración jurada del menor',
 'Minor Sworn Declaration',
 'Narrativa propia del menor — eje central de toda la evidencia. Se construye con la pestaña "Mi Historia".',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, false,
 NULL, 'single', NULL, 190, NULL),

('custodian_affidavit',
 'Declaración jurada del custodio propuesto',
 'Custodian Sworn Declaration',
 'Lo que el custodio sabe directamente sobre la situación del menor.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, false,
 NULL, 'single', NULL, 200, NULL),

('witness_affidavits',
 'Declaraciones juradas de testigos',
 'Witness Sworn Declarations',
 'Familiares, vecinos, amigos. Mínimo 2-3 idealmente.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, false,
 NULL, 'multiple_named', 10, 210, NULL),

('police_reports',
 'Reportes policiales',
 'Police Reports',
 'De país de origen o EE.UU. si hubo denuncias formales.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, false,
 NULL, 'multiple_named', 10, 220, NULL),

('protection_orders',
 'Órdenes de protección o restricción',
 'Protection / Restraining Orders',
 'Si existen contra algún miembro de la familia.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, false,
 NULL, 'multiple_named', 5, 230, NULL),

('medical_records',
 'Expedientes médicos del menor',
 'Minor Medical Records',
 'Lesiones, hospitalizaciones, atención por trauma.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, false,
 NULL, 'multiple_named', 10, 240, NULL),

('mental_health_records',
 'Expedientes de salud mental',
 'Mental Health Records',
 'Diagnósticos de trauma, depresión, ansiedad.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, false,
 NULL, 'multiple_named', 10, 250, NULL),

('school_records',
 'Récords escolares',
 'School Records',
 'Demuestran ausencias, bajo rendimiento, reportes de maestros.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, true,
 NULL, 'multiple_named', 10, 260, NULL),

('teacher_letters',
 'Cartas de maestros, consejeros o trabajadores sociales',
 'Letters from Teachers/Counselors/Social Workers',
 'Observaciones profesionales del comportamiento del menor.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, false,
 NULL, 'multiple_named', 10, 270, NULL),

('religious_letters',
 'Cartas de líderes religiosos / clérigos',
 'Letters from Religious Leaders',
 'Evidencia comunitaria del trato familiar.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, false,
 NULL, 'multiple_named', 5, 280, NULL),

('doctor_letters',
 'Cartas de médicos o pediatras',
 'Letters from Doctors / Pediatricians',
 'Sobre condiciones físicas o emocionales del menor.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, false,
 NULL, 'multiple_named', 5, 290, NULL),

('evidence_photos',
 'Fotos como evidencia',
 'Photos as Evidence',
 'Lesiones, condiciones de vivienda, ausencia parental. Con metadata y fecha si es posible.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 false, false, true, true, false,
 NULL, 'multiple_named', 10, 300, NULL),

('communications',
 'Comunicaciones electrónicas',
 'Electronic Communications',
 'Mensajes, WhatsApp, emails, cartas donde se evidencien insultos, amenazas o abandono.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, false,
 NULL, 'multiple_named', 10, 310, NULL),

('cps_reports',
 'Reportes CPS / DCFS',
 'CPS / DCFS Reports',
 'Si la agencia de protección infantil intervino.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 false, false, true, true, false,
 NULL, 'multiple_named', 5, 320, NULL),

('country_social_services',
 'Reportes de servicios sociales del país de origen',
 'Country Social Services Reports',
 'DIF en México, INABIF en Perú, etc.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, false,
 NULL, 'multiple_named', 5, 330, NULL),

-- ─── Interés superior del menor ───
('country_conditions_reports',
 'Reportes de país sobre condiciones para menores',
 'Country Conditions Reports',
 'U.S. State Department Country Reports, UNICEF, Human Rights Watch.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 false, false, true, true, false,
 NULL, 'multiple_named', 5, 340, NULL),

('country_violence_reports',
 'Reportes sobre violencia / pandillas / trata',
 'Country Violence/Gang/Trafficking Reports',
 'Específicos por país y región.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 false, false, true, true, false,
 NULL, 'multiple_named', 5, 350, NULL),

('threats_evidence',
 'Evidencia de amenazas concretas hacia el menor',
 'Specific Threats Evidence',
 'Si las hay en el país de origen.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 true, false, true, true, false,
 NULL, 'multiple_named', 5, 360, NULL),

('us_school_progress',
 'Récords de progreso escolar del menor en EE.UU.',
 'US School Progress Records',
 'Demuestra integración del menor.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 false, false, true, true, true,
 NULL, 'multiple_named', 10, 370, NULL),

('us_community_letters',
 'Cartas de la comunidad estadounidense',
 'US Community Letters',
 'Escuela, iglesia, deportes — lazos comunitarios establecidos.',
 'evidencia_situacion', 'Evidencia de mi situación', 'gavel',
 false, false, true, true, true,
 NULL, 'multiple_named', 5, 380, NULL),

('care_plan',
 'Plan de cuidado y educación del custodio',
 'Custodian Care Plan',
 'A veces requerido por la corte.',
 'sobre_el_custodio', 'Sobre el custodio y mi hogar', 'home',
 false, false, true, false, false,
 NULL, 'single', NULL, 390, NULL),

-- ─── Documentos condicionales ───
('parent_consent',
 'Consentimiento por escrito del padre/madre vivo(s)',
 'Living Parent Written Consent',
 'Para guardianship en estados como Maryland.',
 'documentos_condicionales', 'Documentos condicionales', 'verified_user',
 true, false, true, false, false,
 NULL, 'single', NULL, 400, NULL),

('foreign_parent_notice',
 'Documentos de notificación a padres en el extranjero',
 'Foreign Parent Service Documents',
 'Cuando se requiere "service" internacional.',
 'documentos_condicionales', 'Documentos condicionales', 'verified_user',
 true, false, true, false, false,
 NULL, 'multiple_named', 5, 410, NULL),

('orr_consent',
 'Carta de no objeción del HHS / ORR',
 'HHS / ORR Consent Letter',
 'Solo si el menor está/estuvo en custodia federal de ORR y la orden estatal cambia su placement.',
 'documentos_condicionales', 'Documentos condicionales', 'verified_user',
 false, false, true, true, false,
 '{"type":"flag_eq","flag":"in_orr_custody","value":true}'::jsonb,
 'single', NULL, 420, NULL),

('attorney_g28',
 'Form G-28 (entrada de aparición de abogado)',
 'Form G-28',
 'Si tienen abogado de inmigración representándolos.',
 'documentos_legales', 'Documentos legales y de la corte', 'account_balance',
 false, false, true, true, true,
 NULL, 'single', NULL, 430, NULL),

-- ─── Formularios USCIS — I-360 ───
('i360_form',
 'Form I-360 firmado',
 'Signed Form I-360',
 'Marcar casilla "c" en Parte 2. Niños 14+ firman ellos mismos.',
 'formularios_uscis', 'Formularios USCIS', 'assignment',
 false, false, false, true, false,
 NULL, 'single', NULL, 440, NULL),

('i360_cover_letter',
 'Carta de presentación a USCIS (I-360)',
 'I-360 Cover Letter',
 'Resume elegibilidad, historia del caso, lista de evidencia.',
 'formularios_uscis', 'Formularios USCIS', 'assignment',
 false, false, false, true, false,
 NULL, 'single', NULL, 450, NULL),

('predicate_order_certified',
 'Predicate Order CERTIFICADA',
 'Certified Predicate Order',
 'Copia certificada con sello del clerk de la corte. NO copia simple.',
 'documentos_legales', 'Documentos legales y de la corte', 'account_balance',
 false, true, false, true, false,
 NULL, 'single', NULL, 460, NULL),

('court_auxiliary_docs',
 'Documentos auxiliares de la corte',
 'Court Auxiliary Documents',
 'Petición original, motion, transcripts si los hay.',
 'documentos_legales', 'Documentos legales y de la corte', 'account_balance',
 false, false, false, true, false,
 NULL, 'multiple_named', 10, 470, NULL),

('uscis_passport_photos',
 'Fotos pasaporte estilo USCIS (2x2 pulgadas)',
 'USCIS Passport-Style Photos (2x2)',
 '2 copias. Tomadas en últimos 30 días.',
 'formularios_uscis', 'Formularios USCIS', 'assignment',
 false, false, false, true, true,
 NULL, 'single', NULL, 480, NULL),

-- ─── Formularios USCIS — I-485 ───
('i797_receipt',
 'Form I-797 — Receipt o Approval del I-360',
 'Form I-797 (I-360 Receipt/Approval)',
 'Comprueba la base del ajuste de estatus.',
 'formularios_uscis', 'Formularios USCIS', 'assignment',
 false, false, false, false, true,
 NULL, 'single', NULL, 490, NULL),

('i485_form',
 'Form I-485 firmado',
 'Signed Form I-485',
 'Marcar la categoría correspondiente en Parte 2.',
 'formularios_uscis', 'Formularios USCIS', 'assignment',
 false, false, false, false, true,
 NULL, 'single', NULL, 500, NULL),

('i693_medical',
 'Form I-693 (examen médico) en sobre sellado',
 'Form I-693 (Medical Exam, Sealed)',
 'Realizado por civil surgeon designado por USCIS. NO abrir el sobre.',
 'formularios_uscis', 'Formularios USCIS', 'assignment',
 false, false, false, false, true,
 NULL, 'single', NULL, 510, NULL),

('passport_full_pages',
 'Pasaporte completo — todas las páginas con sellos',
 'Complete Passport (All Stamped Pages)',
 'Páginas biográficas + todas con sellos/visas.',
 'formularios_uscis', 'Formularios USCIS', 'assignment',
 false, false, false, false, true,
 NULL, 'single', NULL, 520, NULL),

('minor_current_id',
 'Identificación con foto vigente del menor',
 'Minor Current Photo ID',
 'Driver''s license, state ID, school ID, etc.',
 'formularios_uscis', 'Formularios USCIS', 'assignment',
 false, false, false, false, true,
 NULL, 'single', NULL, 530, NULL),

('i485_filing_fee',
 'Pago del filing fee O Form I-912 (fee waiver)',
 'I-485 Filing Fee or Form I-912',
 'Verificar fee actual en uscis.gov/i-485.',
 'formularios_uscis', 'Formularios USCIS', 'assignment',
 false, false, false, false, true,
 NULL, 'single', NULL, 540, NULL),

('criminal_records',
 'Récords criminales certificados',
 'Certified Criminal Records',
 'Cualquier arresto, cargo, condena o adjudicación de delincuencia juvenil — incluso si fue desestimado.',
 'documentos_condicionales', 'Documentos condicionales', 'verified_user',
 true, true, false, false, true,
 '{"type":"flag_eq","flag":"has_criminal_history","value":true}'::jsonb,
 'multiple_named', 10, 550, NULL),

('i601_waiver',
 'Form I-601 — Waiver of Inadmissibility',
 'Form I-601',
 'Si hay causales de inadmisibilidad waivables (presencia ilegal previa, ciertos crímenes, fraude, etc.).',
 'documentos_condicionales', 'Documentos condicionales', 'verified_user',
 false, false, false, false, true,
 '{"type":"flag_eq","flag":"has_criminal_history","value":true}'::jsonb,
 'single', NULL, 560, NULL),

('i601_supporting_docs',
 'Documentación de soporte para waiver I-601',
 'I-601 Supporting Documentation',
 'Hardship evidence, rehabilitación, cartas de apoyo.',
 'documentos_condicionales', 'Documentos condicionales', 'verified_user',
 true, false, false, false, true,
 '{"type":"flag_eq","flag":"has_criminal_history","value":true}'::jsonb,
 'multiple_named', 10, 570, NULL),

('tax_returns',
 'Tax returns (últimos años)',
 'Tax Returns (Recent Years)',
 'Buena moralidad / continuous presence.',
 'formularios_uscis', 'Formularios USCIS', 'assignment',
 false, false, false, false, true,
 NULL, 'multiple_named', 5, 580, NULL),

('i765_ead',
 'Form I-765 (Employment Authorization)',
 'Form I-765 (EAD)',
 'Permiso de trabajo mientras se procesa el I-485. Categoría (c)(9).',
 'formularios_uscis', 'Formularios USCIS', 'assignment',
 false, false, false, false, true,
 NULL, 'single', NULL, 590, NULL),

('i131_advance_parole',
 'Form I-131 (Advance Parole)',
 'Form I-131 (Advance Parole)',
 'Permiso para viajar fuera de EE.UU. mientras I-485 está pendiente.',
 'formularios_uscis', 'Formularios USCIS', 'assignment',
 false, false, false, false, true,
 NULL, 'single', NULL, 600, NULL)

ON CONFLICT (code) DO UPDATE SET
  name_es = EXCLUDED.name_es,
  name_en = EXCLUDED.name_en,
  description_es = EXCLUDED.description_es,
  category_code = EXCLUDED.category_code,
  category_name_es = EXCLUDED.category_name_es,
  category_icon = EXCLUDED.category_icon,
  requires_translation = EXCLUDED.requires_translation,
  requires_certified_copy = EXCLUDED.requires_certified_copy,
  shown_in_custodia = EXCLUDED.shown_in_custodia,
  shown_in_i360 = EXCLUDED.shown_in_i360,
  shown_in_i485 = EXCLUDED.shown_in_i485,
  conditional_logic = EXCLUDED.conditional_logic,
  slot_kind = EXCLUDED.slot_kind,
  max_slots = EXCLUDED.max_slots,
  sort_order = EXCLUDED.sort_order,
  legal_reference = EXCLUDED.legal_reference;
