import type { DemoScript } from '../types'

const CLIENT_NAME = 'Roberto Cárdenas Vásquez'

export const asiloPoliticoScript: DemoScript = {
  serviceSlug: 'asilo-politico',
  serviceName: 'Asilo Político',
  totalDurationMs: 105_000,
  steps: [
    {
      id: 'intro',
      phase: 'asilo_sustentos',
      duration: 5_000,
      narration: 'Asilo Político — el proceso afirmativo I-589 ante USCIS, con declaración jurada generada por IA y miedo creíble.',
      scene: { kind: 'intro', title: 'Asilo Político (I-589)', subtitle: '2 fases: sustentos + reforzar — todo digital y automatizado' },
    },
    {
      id: 'register',
      phase: 'asilo_sustentos',
      duration: 7_500,
      narration: 'Roberto huyó de Venezuela por persecución política. Llega a nuestra plataforma y se registra para iniciar asilo afirmativo.',
      scene: { kind: 'client-register', clientName: CLIENT_NAME, phone: '+1 (305) 555-0182', service: 'Asilo Político' },
    },
    {
      id: 'form-identidad',
      phase: 'asilo_sustentos',
      duration: 10_000,
      narration: 'Fase 1 — Sustentos. Roberto llena su información personal y estatus de ingreso al país. Cada campo se autoguarda.',
      scene: {
        kind: 'form-fill',
        title: 'Identidad y estatus de ingreso',
        section: 'Sustentos · I-589 Parte A',
        fields: [
          { label: 'Nombre completo', value: 'Roberto Cárdenas Vásquez' },
          { label: 'País de nacionalidad', value: 'Venezuela' },
          { label: 'Fecha de ingreso a EE.UU.', value: '12/01/2025' },
          { label: 'Estatus al ingresar', value: 'Parole humanitario CBP One' },
        ],
      },
    },
    {
      id: 'docs-sustentos',
      phase: 'asilo_sustentos',
      duration: 7_500,
      narration: 'Sube sus documentos de identidad, evidencia de persecución y registro de ingreso por CBP.',
      scene: {
        kind: 'document-upload',
        docs: [
          { label: 'Pasaporte venezolano', type: 'PDF · vigente' },
          { label: 'I-94 (CBP One)', type: 'PDF · oficial' },
          { label: 'Citación de SEBIN (persecución)', type: 'PDF · traducida' },
          { label: 'Carnet del partido político', type: 'PDF · escaneado' },
        ],
      },
    },
    {
      id: 'advance-reforzar',
      phase: 'asilo_sustentos',
      duration: 4_500,
      narration: 'Sustentos completos. Avanzamos a la Fase 2 — donde generamos la declaración jurada con IA.',
      scene: {
        kind: 'phase-advance',
        from: 'Sustentos ✓',
        to: 'Fase 2 — Reforzar',
        toDescription: 'Declaración jurada, evidencias y miedo creíble.',
      },
    },
    {
      id: 'form-relato',
      phase: 'asilo_reforzar',
      duration: 11_000,
      narration: 'Roberto cuenta su historia con guía paso a paso — qué pasó, cuándo, por qué teme regresar. La IA después la convierte en declaración legal.',
      scene: {
        kind: 'form-fill',
        title: 'Relato del solicitante',
        section: 'Reforzar · Mi historia',
        fields: [
          { label: 'Motivo de persecución', value: 'Opinión política · oposición al régimen' },
          { label: '¿Sufrió daño en su país?', value: 'Detención arbitraria · amenazas a familia' },
          { label: '¿Quién lo persigue?', value: 'SEBIN — policía política' },
          { label: '¿Por qué teme regresar?', value: 'Orden de captura activa · familia continúa amenazada' },
        ],
      },
    },
    {
      id: 'ai-declaracion',
      phase: 'asilo_reforzar',
      duration: 12_000,
      narration: 'La IA Claude procesa el relato y lo transforma en la Declaración Jurada — 12 páginas en estilo legal, listas para firmar.',
      scene: {
        kind: 'ai-generate',
        title: 'Declaración Jurada — Asilo I-589',
        engine: 'claude',
        output: 'Declaración generada · 12 páginas en estilo legal',
        previewLines: [
          'DECLARACIÓN JURADA EN APOYO A LA SOLICITUD DE ASILO',
          'I-589 — Roberto Cárdenas Vásquez',
          '',
          'Yo, Roberto Cárdenas Vásquez, mayor de edad,',
          'venezolano, declaro bajo pena de perjurio:',
          '',
          '1. Soy ciudadano de la República Bolivariana de Venezuela,',
          '   nacido el 8 de mayo de 1987 en Caracas.',
          '',
          '2. Solicito asilo en los Estados Unidos por temor fundado',
          '   de persecución debido a mi opinión política, conforme a',
          '   la Sección 208 de la Ley INA.',
          '',
          '3. Entre 2022 y 2024 participé activamente en la oposición',
          '   política al gobierno actual de Venezuela...',
        ],
      },
    },
    {
      id: 'ai-miedo-creible',
      phase: 'asilo_reforzar',
      duration: 10_500,
      narration: 'Generamos también la entrevista de Miedo Creíble — preguntas oficiales con respuestas estructuradas para preparar al cliente.',
      scene: {
        kind: 'ai-generate',
        title: 'Preparación · Miedo Creíble',
        engine: 'gemini',
        output: 'Guion de preparación generado · 35 preguntas oficiales',
        previewLines: [
          'PREPARACIÓN PARA ENTREVISTA DE MIEDO CREÍBLE',
          'Asylum Pre-Screening Interview · USCIS',
          '',
          'Q1: Why are you afraid to return to your country?',
          'A: I am afraid because of my political activities...',
          '',
          'Q2: Who specifically would harm you?',
          'A: The SEBIN — political police of the regime...',
          '',
          'Q3: Have you been harmed in the past?',
          'A: Yes. I was detained for 72 hours in 2023...',
        ],
      },
    },
    {
      id: 'admin-review',
      phase: 'asilo_reforzar',
      duration: 6_000,
      narration: 'Henry revisa todo el expediente. Aprueba y el sistema lo deja listo para enviar a USCIS.',
      scene: {
        kind: 'admin-review',
        title: 'Expediente de Asilo — revisión final',
        items: [
          { label: 'Formulario I-589 completo', status: 'aprobado' },
          { label: 'Declaración jurada (IA)', status: 'aprobado' },
          { label: 'Evidencias de persecución (4)', status: 'aprobado' },
          { label: 'Preparación miedo creíble', status: 'aprobado' },
        ],
      },
    },
    {
      id: 'success',
      phase: 'asilo_completado',
      duration: 7_000,
      narration: 'Expediente enviado a USCIS. Roberto queda en la cola con su recibo oficial — el sistema le notifica cualquier movimiento.',
      scene: {
        kind: 'success',
        title: 'Asilo enviado a USCIS',
        subtitle: 'Caso completo presentado · ahora a esperar entrevista de asilo.',
        deliverables: [
          'Formulario I-589 oficial firmado',
          'Declaración jurada de 12 páginas (IA)',
          'Paquete de evidencias indexado',
          'Guion de preparación para miedo creíble',
        ],
      },
    },
  ],
}
