import type { DemoScript } from '../types'

const CLIENT_NAME = 'María Fernanda Quispe'
const CLIENT_PHONE = '+1 (267) 555-0123'

export const visaJuvenilScript: DemoScript = {
  serviceSlug: 'visa-juvenil',
  serviceName: 'Visa Juvenil (SIJS)',
  totalDurationMs: 170_000,
  steps: [
    {
      id: 'intro',
      phase: 'custodia',
      duration: 5_000,
      narration: 'Te muestro cómo funciona el proceso completo de Visa Juvenil — desde que el cliente se registra hasta que llega su Green Card.',
      scene: { kind: 'intro', title: 'Visa Juvenil (SIJS)', subtitle: 'Custodia estatal + I-360 + I-485 — proceso 100% guiado y automatizado' },
    },
    {
      id: 'register',
      phase: 'custodia',
      duration: 9_000,
      narration: 'El cliente llega a nuestra plataforma y completa su registro inicial. El sistema asigna el servicio automáticamente.',
      scene: {
        kind: 'client-register',
        clientName: CLIENT_NAME,
        phone: CLIENT_PHONE,
        service: 'Visa Juvenil (SIJS)',
      },
    },
    {
      id: 'portal-entry',
      phase: 'custodia',
      duration: 5_000,
      narration: 'Recibe su link privado por WhatsApp y entra al portal. Aquí ve sus pestañas: Inicio, Documentos, Formularios, Fases y Citas.',
      scene: {
        kind: 'client-portal',
        clientName: CLIENT_NAME,
        serviceName: 'Visa Juvenil — Fase 1: Custodia',
        tabHighlight: 'Inicio',
      },
    },
    {
      id: 'form-menor',
      phase: 'custodia',
      duration: 11_000,
      narration: 'Empieza con el formulario del menor. Datos básicos, fecha de nacimiento, lugar y estatus migratorio actual.',
      scene: {
        kind: 'form-fill',
        title: 'Información del menor',
        section: 'Custodia · Paso 1 de 4',
        fields: [
          { label: 'Nombre completo del menor', value: 'Sofía Alejandra Quispe' },
          { label: 'Fecha de nacimiento', value: '14/03/2012' },
          { label: 'Lugar de nacimiento', value: 'Cusco, Perú' },
          { label: 'Estatus actual en EE.UU.', value: 'Sin estatus' },
        ],
      },
    },
    {
      id: 'form-padres',
      phase: 'custodia',
      duration: 10_000,
      narration: 'Información de los padres biológicos. Esto es crítico para los hallazgos SIJS — la corte debe declarar que la reunificación no es viable.',
      scene: {
        kind: 'form-fill',
        title: 'Información de los padres',
        section: 'Custodia · Paso 2 de 4',
        fields: [
          { label: 'Nombre del padre', value: 'José Quispe Mamani' },
          { label: 'Paradero del padre', value: 'Desconocido — abandonó al menor en 2018' },
          { label: 'Nombre de la madre', value: 'Carmen Rosa Huamán' },
          { label: 'Paradero de la madre', value: 'Fallecida — 2020' },
        ],
      },
    },
    {
      id: 'form-historia',
      phase: 'custodia',
      duration: 9_000,
      narration: 'La historia de abuso, abandono o negligencia. Este relato lo escribe el tutor con guía nuestra — luego la IA lo transforma en la declaración jurada.',
      scene: {
        kind: 'form-fill',
        title: 'Historia de abuso / abandono / negligencia',
        section: 'Custodia · Paso 3 de 4',
        fields: [
          { label: '¿Qué pasó?', value: 'Padre desapareció · madre falleció · sin red familiar en Perú' },
          { label: 'Tutor actual', value: 'Tía paterna — Lucía Quispe (Florida)' },
          { label: 'Tiempo bajo cuidado del tutor', value: 'Desde junio 2022' },
        ],
      },
    },
    {
      id: 'docs-custodia',
      phase: 'custodia',
      duration: 8_000,
      narration: 'El cliente sube los documentos. Cada uno tiene una sección clara en su portal — sin confusión.',
      scene: {
        kind: 'document-upload',
        docs: [
          { label: 'Acta de nacimiento del menor', type: 'PDF · traducida' },
          { label: 'Acta de defunción de la madre', type: 'PDF · traducida' },
          { label: 'Pasaporte del menor', type: 'PDF · escaneado' },
          { label: 'ID del tutor', type: 'PDF · ambos lados' },
          { label: 'Comprobante de domicilio del tutor', type: 'PDF · últimos 3 meses' },
        ],
      },
    },
    {
      id: 'ai-peticion-custodia',
      phase: 'custodia',
      duration: 11_000,
      narration: 'Aquí entra la IA. Gemini procesa toda la información y genera la petición de custodia completa con los hallazgos SIJS — listos para la corte estatal.',
      scene: {
        kind: 'ai-generate',
        title: 'Petición de Custodia con hallazgos SIJS',
        engine: 'gemini',
        output: 'Documento generado · 14 páginas',
        previewLines: [
          'IN THE CIRCUIT COURT FOR MIAMI-DADE COUNTY, FLORIDA',
          'PETITION FOR APPOINTMENT OF GUARDIAN',
          '',
          'COMES NOW, Petitioner Lucía Quispe, paternal aunt of the',
          'minor child Sofía Alejandra Quispe (born 14 March 2012),',
          'and respectfully petitions this Honorable Court for the',
          'appointment of permanent guardianship.',
          '',
          'SIJS FINDINGS REQUESTED:',
          '1. The minor is dependent on this Court',
          '2. Reunification with parents is not viable due to',
          '   abandonment and death',
          '3. Return to country of origin is not in best interest',
        ],
      },
    },
    {
      id: 'admin-review-custodia',
      phase: 'custodia',
      duration: 6_000,
      narration: 'Henry revisa todo en su panel de admin. Aprueba el expediente con un clic y avanza al cliente a Fase 2.',
      scene: {
        kind: 'admin-review',
        title: 'Revisión del expediente — Fase Custodia',
        items: [
          { label: 'Formulario del menor', status: 'aprobado' },
          { label: 'Información de los padres', status: 'aprobado' },
          { label: 'Historia de abandono', status: 'aprobado' },
          { label: 'Documentos del menor (5)', status: 'aprobado' },
          { label: 'Petición de custodia (IA)', status: 'aprobado' },
        ],
      },
    },
    {
      id: 'advance-i360',
      phase: 'custodia',
      duration: 4_500,
      narration: 'La corte estatal emite la orden de custodia. El sistema avanza automáticamente al cliente a la Fase 2 — I-360.',
      scene: {
        kind: 'phase-advance',
        from: 'Custodia ✓',
        to: 'Fase 2 — I-360',
        toDescription: 'Petición SIJS ante USCIS. Aquí se demuestra que el menor califica como Inmigrante Juvenil Especial.',
      },
    },
    {
      id: 'docs-i360',
      phase: 'i360',
      duration: 6_500,
      narration: 'Documentos clave de esta fase: la orden de la corte estatal con los hallazgos SIJS firmados por el juez.',
      scene: {
        kind: 'document-upload',
        docs: [
          { label: 'Orden de custodia firmada por el juez', type: 'PDF · sellada' },
          { label: 'Hallazgos SIJS (Predicate Order)', type: 'PDF · oficial' },
          { label: 'Carta de tutor explicando situación', type: 'PDF · firmada' },
        ],
      },
    },
    {
      id: 'ai-i360',
      phase: 'i360',
      duration: 9_500,
      narration: 'La IA ahora genera el Formulario I-360 prerellenado. 28 páginas oficiales de USCIS con cada campo en su lugar.',
      scene: {
        kind: 'ai-generate',
        title: 'Formulario I-360 — Special Immigrant Juvenile',
        engine: 'claude',
        output: 'Formulario completo · 28 páginas · listo para enviar',
        previewLines: [
          'DEPARTMENT OF HOMELAND SECURITY · USCIS',
          'FORM I-360 · PETITION FOR SPECIAL IMMIGRANT',
          '',
          'Part 1 — Information about the person filing',
          '   Name: Sofía Alejandra Quispe',
          '   Date of Birth: 14 MAR 2012',
          '',
          'Part 2 — Classification requested',
          '   ☒ Special Immigrant Juvenile',
          '',
          'Part 3 — Information about the petitioner',
          '   Guardian: Lucía Quispe',
          '   Court order date: 12 SEP 2025',
        ],
      },
    },
    {
      id: 'admin-i360',
      phase: 'i360',
      duration: 5_500,
      narration: 'Diana, paralegal, hace la revisión final antes de enviar a USCIS.',
      scene: {
        kind: 'admin-review',
        title: 'Revisión final — I-360',
        items: [
          { label: 'Orden de custodia adjunta', status: 'aprobado' },
          { label: 'Hallazgos SIJS verificados', status: 'aprobado' },
          { label: 'Formulario I-360 (28 pp)', status: 'aprobado' },
          { label: 'Documentos de soporte', status: 'aprobado' },
        ],
      },
    },
    {
      id: 'advance-i485',
      phase: 'i360',
      duration: 4_500,
      narration: 'USCIS aprueba el I-360. Avanzamos a la última fase — el ajuste de estatus.',
      scene: {
        kind: 'phase-advance',
        from: 'I-360 ✓',
        to: 'Fase 3 — I-485',
        toDescription: 'Ajuste de Estatus a Residente Permanente Legal (Green Card).',
      },
    },
    {
      id: 'form-i485',
      phase: 'i485',
      duration: 9_000,
      narration: 'Datos finales del menor para el ajuste de estatus. Información médica, historial migratorio reciente y dirección actual.',
      scene: {
        kind: 'form-fill',
        title: 'Datos para el I-485',
        section: 'Ajuste de Estatus · Paso final',
        fields: [
          { label: 'Dirección actual', value: '4521 NW 7th Ave, Miami, FL 33127' },
          { label: 'Examen médico (I-693)', value: 'Completado · 03/03/2026' },
          { label: 'Historial de viajes recientes', value: 'Sin viajes desde ingreso' },
        ],
      },
    },
    {
      id: 'ai-i485',
      phase: 'i485',
      duration: 10_000,
      narration: 'La IA arma el paquete I-485 completo: formulario oficial, evidencias médicas, fotografías, comprobantes — todo en orden.',
      scene: {
        kind: 'ai-generate',
        title: 'Paquete I-485 — Ajuste de Estatus',
        engine: 'claude',
        output: 'Paquete completo · 87 páginas · listo para enviar a USCIS',
        previewLines: [
          'FORM I-485 · APPLICATION TO REGISTER PERMANENT RESIDENCE',
          '',
          'Part 1 — Information about you',
          '   A-Number: A 287-654-321',
          '   I-94 Number: 12345678901',
          '',
          'Part 2 — Application type',
          '   ☒ Special Immigrant Juvenile (approved I-360)',
          '',
          'Supporting documents included:',
          '   ✓ Form I-693 (Medical Examination)',
          '   ✓ Form I-864W (Affidavit of Support exemption)',
          '   ✓ Passport-style photos (2)',
          '   ✓ Approved I-360 receipt notice',
        ],
      },
    },
    {
      id: 'success',
      phase: 'completado',
      duration: 9_000,
      narration: 'Listo. El paquete sale para USCIS y el cliente entra a la lista de espera de Green Card. Todo digital, trazable, sin papeles perdidos.',
      scene: {
        kind: 'success',
        title: '¡Caso completado!',
        subtitle: 'María Fernanda y su sobrina Sofía cierran el proceso SIJS — ahora a esperar la Green Card.',
        deliverables: [
          'Petición de custodia con hallazgos SIJS (14 pp)',
          'Formulario I-360 aprobado por USCIS (28 pp)',
          'Paquete I-485 enviado (87 pp)',
          'Expediente completo accesible para el cliente y el admin',
        ],
      },
    },
  ],
}
